In [1]:
import numpy as np
import pandas as pd

### Creating dataset --

In [18]:
from sklearn.datasets import make_classification

x, y = make_classification(n_samples=1000, n_features=10, random_state=42, n_informative=3,  n_classes=3)

In [19]:
# train test split --
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.30, random_state=42)

### Model Implementing --

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
regression = LogisticRegression(multi_class='ovr')

In [23]:
regression.fit(x_train, y_train)

C:\Users\anupa\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [24]:
y_pred = regression.predict(x_test)

In [25]:
# Model evaluation ---
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print('Accurecy - ', accuracy_score(y_test, y_pred))
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print(classification_report(y_test, y_pred))

[[79 16  8]
 [31 38 27]
 [ 3 11 87]]
Accurecy -  0.68
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300



### Hyperparameter Tuning---
#### GridSearchCV

In [26]:
from sklearn.model_selection import GridSearchCV

In [32]:
model = LogisticRegression()
param_grid = [
    {
        'penalty': ['l1'],
        'solver': ['liblinear', 'saga'],
        'C': [0.01, 0.1, 1, 10, 100]
    },
    {
        'penalty': ['l2'],
        'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
        'C': [0.01, 0.1, 1, 10, 100]
    },
    {
        'penalty': ['elasticnet'],
        'solver': ['saga'],
        'C': [0.01, 0.1, 1, 10, 100],
        'l1_ratio' : [0.001, 0.004, 0.006, 0.02, 0.1]
    }
]

In [33]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=5)

In [34]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=cv, scoring='accuracy')

In [35]:
grid.fit(x_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [0.01, 0.1, 1, 10, 100],
                          'l1_ratio': [0.001, 0.004, 0.006, 0.02, 0.1],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [36]:
print(grid.best_params_)
print(grid.best_score_)

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}
0.6528571428571428


In [37]:
grid_y_pred = grid.predict(x_test)

In [38]:
print(confusion_matrix(y_test, grid_y_pred))
print('Accurecy - ', accuracy_score(y_test, grid_y_pred))
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print(classification_report(y_test, grid_y_pred))

[[78 17  8]
 [28 43 25]
 [ 3  8 90]]
Accurecy -  0.7033333333333334
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              precision    recall  f1-score   support

           0       0.72      0.76      0.74       103
           1       0.63      0.45      0.52        96
           2       0.73      0.89      0.80       101

    accuracy                           0.70       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.69      0.70      0.69       300



### Hyperparameter Tuning---
#### RandomizedCV

In [39]:
from sklearn.model_selection import RandomizedSearchCV

In [40]:
model = LogisticRegression()
param_grid = [
    {
        'penalty': ['l1'],
        'solver': ['liblinear', 'saga'],
        'C': [0.01, 0.1, 1, 10, 100]
    },
    {
        'penalty': ['l2'],
        'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
        'C': [0.01, 0.1, 1, 10, 100]
    },
    {
        'penalty': ['elasticnet'],
        'solver': ['saga'],
        'C': [0.01, 0.1, 1, 10, 100],
        'l1_ratio' : [0.001, 0.004, 0.006, 0.02, 0.1]
    }
]

In [42]:
randcv = RandomizedSearchCV(estimator=model, param_distributions=param_grid, cv=cv, scoring='accuracy', n_jobs=-1)

In [43]:
randcv.fit(x_train, y_train)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions=[{'C': [0.01, 0.1, 1, 10, 100],
                                         'penalty': ['l1'],
                                         'solver': ['liblinear', 'saga']},
                                        {'C': [0.01, 0.1, 1, 10, 100],
                                         'penalty': ['l2'],
                                         'solver': ['newton-cg', 'lbfgs',
                                                    'liblinear', 'sag',
                                                    'saga']},
                                        {'C': [0.01, 0.1, 1, 10, 100],
                                         'l1_ratio': [0.001, 0.004, 0.006, 0.02,
                                                      0.1],
                                         'penalty': ['elasticnet'],
                                         'solver': ['saga']}],
                   scoring='accuracy')

In [44]:
print(randcv.best_params_)
print(randcv.best_score_)

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.01}
0.63


In [45]:
rand_y_pred = randcv.predict(x_test)

In [46]:
print(confusion_matrix(y_test, rand_y_pred))
print('Accurecy - ', accuracy_score(y_test, rand_y_pred))
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print(classification_report(y_test, rand_y_pred))

[[76 20  7]
 [25 47 24]
 [ 3 11 87]]
Accurecy -  0.7
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              precision    recall  f1-score   support

           0       0.73      0.74      0.73       103
           1       0.60      0.49      0.54        96
           2       0.74      0.86      0.79       101

    accuracy                           0.70       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.69      0.70      0.69       300

