In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Make Datasets ---

In [2]:
# Make dataset --
from sklearn.datasets import make_classification

In [3]:
x, y = make_classification(n_samples=10000, n_features=10, random_state=42, n_classes=2)

In [4]:
# train test split --
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.30, random_state=42)

## Simple Logistic Implementation --

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
logistic = LogisticRegression()

In [7]:
logistic.fit(x_train, y_train)

LogisticRegression()

In [8]:
y_pred = logistic.predict(x_test)

In [9]:
y_pred

array([1, 1, 1, ..., 0, 1, 0])

In [10]:
# Model evaluation ---
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [11]:
print(confusion_matrix(y_test, y_pred))
print('Accurecy - ', accuracy_score(y_test, y_pred))
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print(classification_report(y_test, y_pred))

[[1329  155]
 [ 168 1348]]
Accurecy -  0.8923333333333333
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              precision    recall  f1-score   support

           0       0.89      0.90      0.89      1484
           1       0.90      0.89      0.89      1516

    accuracy                           0.89      3000
   macro avg       0.89      0.89      0.89      3000
weighted avg       0.89      0.89      0.89      3000



## Hyperparameter Tuning ---

In [12]:
from sklearn.model_selection import GridSearchCV

In [38]:
model = LogisticRegression()
param = [
    {
        'penalty': ['l1'],
        'solver': ['liblinear', 'saga'],
        'C': [0.01, 0.1, 1, 10, 100]
    },
    {
        'penalty': ['l2'],
        'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
        'C': [0.01, 0.1, 1, 10, 100]
    },
    {
        'penalty': ['elasticnet'],
        'solver': ['saga'],
        'C': [0.01, 0.1, 1, 10, 100],
        'l1_ratio' : [0.01, 0.1, 0.2, 0.9, 0.8]
    }
]

In [39]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=5)

In [40]:
grid = GridSearchCV(estimator=model, param_grid=param, cv=cv, scoring="accuracy", n_jobs=-1)

In [41]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [0.01, 0.1, 1, 10, 100],
                          'l1_ratio': [0.01, 0.1, 0.2, 0.9, 0.8],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [42]:
grid.fit(x_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [0.01, 0.1, 1, 10, 100],
                          'l1_ratio': [0.01, 0.1, 0.2, 0.9, 0.8],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [46]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'liblinear'}

In [47]:
grid.best_score_

np.float64(0.8917142857142857)

In [48]:
grid_y_pred = grid.predict(x_test)

array([1, 1, 1, ..., 0, 0, 0])

In [50]:
print(confusion_matrix(y_test, grid_y_pred))
print('Accurecy - ', accuracy_score(y_test, grid_y_pred))
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print(classification_report(y_test, grid_y_pred))

[[1332  152]
 [ 163 1353]]
Accurecy -  0.895
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              precision    recall  f1-score   support

           0       0.89      0.90      0.89      1484
           1       0.90      0.89      0.90      1516

    accuracy                           0.90      3000
   macro avg       0.89      0.90      0.89      3000
weighted avg       0.90      0.90      0.90      3000



### Fine Tuning ---

In [61]:
param = {
    'C': [0.0001, 0.001, 0.002, 0.005],
    'penalty': ['l1'],
    'solver': ['liblinear']
}
grid = GridSearchCV(estimator=model, param_grid=param, cv=cv, scoring="accuracy", n_jobs=-1)

grid.fit(x_train, y_train)

print(grid.best_params_)
print(grid.best_score_)

{'C': 0.005, 'penalty': 'l1', 'solver': 'liblinear'}
0.8880000000000001


## RandomizedCV Hyperparameter Tuning ---

In [62]:
from sklearn.model_selection import RandomizedSearchCV

In [63]:
model = LogisticRegression()
param = [
    {
        'penalty': ['l1'],
        'solver': ['liblinear', 'saga'],
        'C': [0.01, 0.1, 1, 10, 100]
    },
    {
        'penalty': ['l2'],
        'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
        'C': [0.01, 0.1, 1, 10, 100]
    },
    {
        'penalty': ['elasticnet'],
        'solver': ['saga'],
        'C': [0.01, 0.1, 1, 10, 100],
        'l1_ratio' : [0.01, 0.1, 0.2, 0.9, 0.8]
    }
]

In [64]:
randcv = RandomizedSearchCV(estimator=model, param_distributions=param, cv=5, scoring='accuracy', n_jobs=-1)

In [65]:
randcv.fit(x_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions=[{'C': [0.01, 0.1, 1, 10, 100],
                                         'penalty': ['l1'],
                                         'solver': ['liblinear', 'saga']},
                                        {'C': [0.01, 0.1, 1, 10, 100],
                                         'penalty': ['l2'],
                                         'solver': ['newton-cg', 'lbfgs',
                                                    'liblinear', 'sag',
                                                    'saga']},
                                        {'C': [0.01, 0.1, 1, 10, 100],
                                         'l1_ratio': [0.01, 0.1, 0.2, 0.9, 0.8],
                                         'penalty': ['elasticnet'],
                                         'solver': ['saga']}],
                   scoring='accuracy')

In [66]:
randcv.best_params_

{'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2, 'C': 0.01}

In [67]:
randcv.best_score_

np.float64(0.8908571428571429)

In [68]:
randcv_y_pred = randcv.predict(x_test)

In [69]:
print(confusion_matrix(y_test, randcv_y_pred))
print('Accurecy - ', accuracy_score(y_test, randcv_y_pred))
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print(classification_report(y_test, randcv_y_pred))

[[1339  145]
 [ 168 1348]]
Accurecy -  0.8956666666666667
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              precision    recall  f1-score   support

           0       0.89      0.90      0.90      1484
           1       0.90      0.89      0.90      1516

    accuracy                           0.90      3000
   macro avg       0.90      0.90      0.90      3000
weighted avg       0.90      0.90      0.90      3000

